name: Build app and deploy to tencent cloud
on:
  #监听push操作，在进行 git push 时会执行这个 action
  push:
    branches:
      # master分支，你也可以改成其他分支
      - master
jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 获取源码
      - name: Checkout
        # 使用action库  actions/checkout获取源码
        uses: actions/checkout@master
      # 安装 Node-16
      - name: use Node.js 16.13.2
        # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.2
      # 安装依赖
      - name: npm install
        run: npm install
      # 打包
      - name: npm run docs:build
        run: npm run docs:build
      # 部署到腾讯云
      - name: Deploy to Tencent Cloud
        uses: easingthemes/ssh-deploy@v2.1.1
        env:
          # 私钥
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录，编译后生成的文件目录
          SOURCE: "./docs/.vuepress/dist"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: "101.32.26.151"
          # 用户
          REMOTE_USER: "root"
          # 目标地址 你在服务器上部署代码的地方
          TARGET: "/www/fdmse"
